ALTER TABLE STUDENT
ALTER COLUMN GTA_CERT_LOCATION VARCHAR(50);

ALTER TABLE STUDENT
ADD CONSTRAINT GPAVALS CHECK(GPA <= 4.0 AND GPA >= 0.0);

ALTER TABLE STUDENT
ALTER COLUMN  GRADE_LEVEL VARCHAR(10) NOT NULL;

CREATE PROCEDURE studentAdd
	@SID int,
	@FIRSTN VARCHAR(20),
	@LASTN VARCHAR(20),
	@YEARGRAD INT,
	@EMAIL VARCHAR(50),
	@PHONE INT,
	@GTACERTLOC VARCHAR(50) = NULL,
	@GTATERM DATE = NULL,
	@INTERNATL BIT = 0,
	@GRADELEVEL VARCHAR(10),
	@GPA FLOAT,
	@HOURSCOMPLETED INT,
	@SEMESTERSCOMPLETED INT,
	@CURRENTMAJOR VARCHAR(50),
	@UNDERGRADDEGREETYPE VARCHAR(50)

AS
	SET NOCOUNT ON;
	INSERT INTO STUDENT
	VALUES (@SID, @FIRSTN, @LASTN, @YEARGRAD, 
	@EMAIL, @PHONE, @GTACERTLOC, @GTATERM, @INTERNATL, @GRADELEVEL,
	@GPA, @HOURSCOMPLETED, @SEMESTERSCOMPLETED, @CURRENTMAJOR, @UNDERGRADDEGREETYPE);
GO


CREATE PROCEDURE jobAdd
	@CLASSID INT,
	@JOBID INT,
	@JOBTITLE VARCHAR(50),
	@TEACHER VARCHAR(50),
	@JOBSTATUS VARCHAR(50) = "UNFILLED",
	@JOBDESCRIPTION VARCHAR(250)
AS
	SET NOCOUNT ON;
	INSERT INTO JOB
	VALUES (@CLASSID, @JOBID, @JOBTITLE, @TEACHER, @JOBSTATUS, @JOBDESCRIPTION);
GO


CREATE PROCEDURE classesAdd
	@CLASSID INT,
	@TERM DATETIME,
	@DEPARTMENT VARCHAR(1),
	@SECTION INT,
	@CLASSDESCRIPTION VARCHAR(280)
AS
	SET NOCOUNT ON;
	INSERT INTO CLASSES
	VALUES (@CLASSID, @TERM, @DEPARTMENT,@SECTION, @CLASSDESCRIPTION);
GO


CREATE PROCEDURE jobrequirementsAdd
	@JOBID INT,
	@CLASSID INT,
	@GRADE FLOAT
AS
	INSERT INTO JOB_REQUIREMENTS
	VALUES (@JOBID, @CLASSID, @GRADE);
GO

CREATE PROCEDURE applicationsAdd
	@SID INT,
	@JOBID INT
AS
	SET NOCOUNT ON;
	INSERT INTO APPLICATIONS
	VALUES(@SID, @JOBID);
GO

CREATE PROCEDURE classestakenAdd
	@SID INT,
	@CLASSID INT,
	@GRADE FLOAT,
	@ATUMKC BIT = 1,
	@LOCATIONTAKEN VARCHAR(50) = "UMKC",
	@TERM DATE
AS
	SET NOCOUNT ON
	INSERT INTO CLASSES_TAKEN
	VALUES(	@SID, @CLASSID, @GRADE, @ATUMKC, @LOCATIONTAKEN, @TERM);
GO

CREATE PROCEDURE termAdd
	@CLASSID INT,
	@TERM DATE,
	@SECTION INT
AS
	SET NOCOUNT ON
	INSERT INTO CLASS_TERMS
	VALUES(@CLASSID, @TERM, @SECTION);
GO
