CREATE PROCEDURE studentAdd
	@SID int,
	@FIRSTN VARCHAR(30),
	@LASTN VARCHAR(30),
	@YEARGRAD INT,
	@EMAIL VARCHAR(70),
	@PHONE INT,
	@GTACERTLOC VARCHAR(50) = NULL,
	@GTATERM DATE = NULL,
	@INTERNATL BIT = 0,
	@GRADELEVEL VARCHAR,
	@GPA FLOAT,
	@HOURSCOMPLETED INT,
	@SEMESTERSCOMPLETED INT,
	@CURRENTMAJOR VARCHAR(50),
	@UNDERGRADDEGREETYPE VARCHAR(50)

AS
	SET NOCOUNT ON;
	INSERT INTO STUDENT
	VALUES (@SID, @FIRSTN, @LASTN, @YEARGRAD, 
	@EMAIL, @PHONE, @GTACERTLOC, @GTATERM, @INTERNATL, @GRADELEVEL,
	@GPA, @HOURSCOMPLETED, @SEMESTERSCOMPLETED, @CURRENTMAJOR, @UNDERGRADDEGREETYPE);
GO

CREATE PROCEDURE jobAdd
	@CLASSID INT,
	@JOBID INT,
	@JOBTITLE VARCHAR(50),
	@TEACHER VARCHAR(50),
	@JOBSTATUS VARCHAR(50) = "UNFILLED",
	@JOBDESCRIPTION VARCHAR(280)
AS
	SET NOCOUNT ON;
	INSERT INTO JOB
	VALUES (@CLASSID, @JOBID, @JOBTITLE, @TEACHER, @JOBSTATUS, @JOBDESCRIPTION);
GO

CREATE PROCEDURE classesAdd
	@CLASSID INT,
	@TERM DATETIME,
	@DEPARTMENT VARCHAR(30),
	@SECTION INT,
	@CLASSDESCRIPTION VARCHAR(250)
AS
	SET NOCOUNT ON;
	INSERT INTO CLASSES
	VALUES (@CLASSID, @TERM, @DEPARTMENT,@SECTION, @CLASSDESCRIPTION);
GO

CREATE PROCEDURE jobrequirementsAdd
	@JOBID INT,
	@CLASSID INT,
	@GRADE VARCHAR(2)
AS
	INSERT INTO JOB_REQUIREMENTS
	VALUES (@JOBID, @CLASSID, @GRADE);
GO

CREATE PROCEDURE applicationsAdd
	@SID INT,
	@JOBID INT
AS
	SET NOCOUNT ON;
	INSERT INTO APPLICATIONS
	VALUES(@SID, @JOBID);
GO

CREATE PROCEDURE classestakenAdd
	@SID INT,
	@CLASSID INT,
	@GRADE VARCHAR(2),
	@ATUMKC BIT = 1,
	@LOCATIONTAKEN VARCHAR(50) = "UMKC"
AS
	SET NOCOUNT ON
	INSERT INTO CLASSES_TAKEN
	VALUES(	@SID, @CLASSID, @GRADE, @ATUMKC, @LOCATIONTAKEN);
GO



