ALTER TABLE STUDENT
DROP COLUMN AGE;
GO

ALTER TABLE STUDENT
ADD EMAIL VARCHAR, 
PHONE INT,
GTA_CERT_LOCATION VARCHAR, 
GTA_TERM DATE, 
INTERNATL BIT, 
GRADE_LEVEL VARCHAR,
GPA FLOAT, 
HOURS_COMPLETED INT, 
SEMESTERS_COMPLETED INT, 
CURRENT_MAJOR_FEILD VARCHAR, 
UNDERGRAD_DEGREE_TYPE VARCHAR;
GO

SELECT * FROM CLASSES
EXEC sp_rename 'CLASSES.SDATE', 'CLASSES.TERM', 'Column';
GO

ALTER TABLE CLASSES_TAKEN
ADD AT_UMKC BIT NOT NULL,
LOCATION_TAKEN VARCHAR;

ALTER TABLE CLASSES
ADD SECTION INT,
CLASS_DESCRIPTION VARCHAR NOT NULL;
GO

ALTER TABLE JOB
ADD JOB_DESCRIPTION VARCHAR NOT NULL;
GO

ALTER TABLE JOB_REQUIREMENTS
ADD GRADE INT;
GO

