CREATE TABLE STUDENT
(STUDENTID INT NOT NULL,
FIRST_NAME VARCHAR NOT NULL,
LAST_NAME VARCHAR NOT NULL,
AGE INT NOT NULL,
YEAR_GRAD INT NOT NULL,
CONSTRAINT PKSTUDENT PRIMARY KEY(STUDENTID)
);

CREATE TABLE CLASSES
(CLASSID INT NOT NULL,
SDATE DATETIME NOT NULL,
DEPARTMENT VARCHAR NOT NULL,
CONSTRAINT PKCLASSES PRIMARY KEY(CLASSID)
);

-- THIS TABLE IS TO ENFORCE JOB TITLES AVAILABLE
CREATE TABLE JOBTITLES
(TITLE VARCHAR
CONSTRAINT PKJOBTITLES PRIMARY KEY(TITLE)
);

-- THIS TABLE IS TO ENFORCE DEPARTNMENTS AVAILABLE
CREATE TABLE DEPARTMENTS
(DEPTNAME VARCHAR
CONSTRAINT PKDEPARTMENTS PRIMARY KEY(DEPTNAME)
);

CREATE TABLE JOB
(CLASSID INT NOT NULL,
JOB_ID INT NOT NULL,
JOB_TITLE VARCHAR,
TEACHER VARCHAR,
FILLED_STATUS CHAR,
CONSTRAINT PKJOB PRIMARY KEY(JOB_ID),
CONSTRAINT JOBFKCLASSES FOREIGN KEY(CLASSID) REFERENCES CLASSES(CLASSID)
ON DELETE CASCADE,
CONSTRAINT TRUEFALSE CHECK(FILLED_STATUS IN('T', 'F'))
);

CREATE TABLE DOCUMENTS
(STUDENTID INT NOT NULL,
DOCUMENT VARCHAR,
CONSTRAINT PKDOCUMENTS PRIMARY KEY(DOCUMENT),
CONSTRAINT DOCUMENTSSTUDENT FOREIGN KEY(STUDENTID) REFERENCES STUDENT(STUDENTID)
ON DELETE CASCADE
);

CREATE TABLE APPLICATIONS
(STUDENTID INT NOT NULL,
JOBID INT NOT NULL,
CONSTRAINT PKAPPLICATIONS PRIMARY KEY(STUDENTID, JOBID),
CONSTRAINT APPLICATIONSFKSTUDENT FOREIGN KEY(STUDENTID) REFERENCES STUDENT(STUDENTID)
ON DELETE CASCADE,
CONSTRAINT APPLICATIONSFKJOB FOREIGN KEY(JOBID) REFERENCES JOB(JOB_ID)
ON DELETE CASCADE
);

CREATE TABLE CLASSES_TAKEN
(STUDENTID INT NOT NULL,
CLASSID INT NOT NULL,
GRADE VARCHAR NOT NULL,
CONSTRAINT PKCLASSES_TAKEN PRIMARY KEY(STUDENTID, CLASSID),
CONSTRAINT FKCLASSES_TAKENFKSTUDENT FOREIGN KEY(STUDENTID) REFERENCES STUDENT(STUDENTID)
ON DELETE CASCADE,
CONSTRAINT CLASSES_TAKENFKCLASSES FOREIGN KEY(CLASSID) REFERENCES CLASSES(CLASSID)
ON DELETE CASCADE
);

CREATE TABLE JOB_REQUIREMENTS
(JOBID INT NOT NULL,
CLASSID INT NOT NULL
CONSTRAINT PKJOB_REQUIREMENTS PRIMARY KEY(JOBID, CLASSID),
CONSTRAINT JOB_REQUIREMENTSFKJOBID FOREIGN KEY(JOBID) REFERENCES JOB(JOB_ID)
ON DELETE CASCADE,
CONSTRAINT JOB_REQUIREMENTSFKCLASSID FOREIGN KEY(CLASSID) REFERENCES CLASSES(CLASSID)
);

go

CREATE TRIGGER CLASS_DELETE
ON CLASSES
INSTEAD OF DELETE
AS
BEGIN
DELETE FROM JOB_REQUIREMENTS
WHERE CLASSID IN (SELECT CLASSID FROM DELETED)
END
GO