CREATE TABLE STUDENT
(STUDENTID INT NOT NULL,
FIRST_NAME VARCHAR(20) NOT NULL,
LAST_NAME VARCHAR(20) NOT NULL,
YEAR_GRAD INT NOT NULL,
EMAIL VARCHAR(50) NOT NULL,
PHONE INT NOT NULL,
GTA_CERT_LOCATION VARCHAR(50),
GTA_TERM DATE,
INTERNATL BIT,
GRADE_LEVEL VARCHAR(1) NOT NULL,
GPA FLOAT,
HOURS_COMPLETE INT,
SEMESTERS_COMPLETED INT,
CURRENT_MAJOR_FEILD VARCHAR(50),
UNDERGRAD_DEGREE_TYPE VARCHAR(50),

CONSTRAINT PKSTUDENT PRIMARY KEY(STUDENTID),
CONSTRAINT GRADEFORMAT CHECK (GRADE_LEVEL = 'M' OR GRADE_LEVEL = 'U')
);


CREATE TABLE CLASSES
(CLASSID INT NOT NULL,
DEPARTMENT VARCHAR(50) NOT NULL,
CLASS_DESCRIPTION VARCHAR(280),
CLASS_NAME VARCHAR(20),

CONSTRAINT PKCLASSES PRIMARY KEY(CLASSID)
);


CREATE TABLE CLASS_TERMS (
CLASSID INT NOT NULL,
TERM DATE NOT NULL,
SECTION INT,


CONSTRAINT PKCLASS_TERMS PRIMARY KEY(CLASSID, TERM),
CONSTRAINT CLASS_TERMSFKCLASS FOREIGN KEY(CLASSID) REFERENCES CLASSES(CLASSID)
ON DELETE CASCADE
);

--fix this part next


CREATE TABLE JOB
(CLASSID INT NOT NULL,
JOB_ID INT NOT NULL,
JOB_TITLE VARCHAR(50) NOT NULL,
TEACHER VARCHAR(50),
FILLED_STATUS INT,
CONSTRAINT PKJOB PRIMARY KEY(JOB_ID),
CONSTRAINT JOBFKCLASSES FOREIGN KEY(CLASSID) REFERENCES CLASSES(CLASSID)
ON DELETE CASCADE,
CONSTRAINT TRUEFALSE CHECK(FILLED_STATUS IN('T', 'F'))
);

CREATE TABLE DOCUMENTS
(STUDENTID INT NOT NULL,
DOCUMENT VARCHAR,
CONSTRAINT PKDOCUMENTS PRIMARY KEY(DOCUMENT),
CONSTRAINT DOCUMENTSSTUDENT FOREIGN KEY(STUDENTID) REFERENCES STUDENT(STUDENTID)
ON DELETE CASCADE
);

CREATE TABLE APPLICATIONS
(STUDENTID INT NOT NULL,
JOBID INT NOT NULL,
CONSTRAINT PKAPPLICATIONS PRIMARY KEY(STUDENTID, JOBID),
CONSTRAINT APPLICATIONSFKSTUDENT FOREIGN KEY(STUDENTID) REFERENCES STUDENT(STUDENTID)
ON DELETE CASCADE,
CONSTRAINT APPLICATIONSFKJOB FOREIGN KEY(JOBID) REFERENCES JOB(JOB_ID)
ON DELETE CASCADE
);

CREATE TABLE CLASSES_TAKEN
(STUDENTID INT NOT NULL,
CLASSID INT NOT NULL,
GRADE VARCHAR NOT NULL,
CONSTRAINT PKCLASSES_TAKEN PRIMARY KEY(STUDENTID, CLASSID),
CONSTRAINT FKCLASSES_TAKENFKSTUDENT FOREIGN KEY(STUDENTID) REFERENCES STUDENT(STUDENTID)
ON DELETE CASCADE,
CONSTRAINT CLASSES_TAKENFKCLASSES FOREIGN KEY(CLASSID) REFERENCES CLASSES(CLASSID)
ON DELETE CASCADE
);

CREATE TABLE JOB_REQUIREMENTS
(JOBID INT NOT NULL,
CLASSID INT NOT NULL
CONSTRAINT PKJOB_REQUIREMENTS PRIMARY KEY(JOBID, CLASSID),
CONSTRAINT JOB_REQUIREMENTSFKJOBID FOREIGN KEY(JOBID) REFERENCES JOB(JOB_ID)
ON DELETE CASCADE,
CONSTRAINT JOB_REQUIREMENTSFKCLASSID FOREIGN KEY(CLASSID) REFERENCES CLASSES(CLASSID)
);

go

CREATE TRIGGER CLASS_DELETE
ON CLASSES
INSTEAD OF DELETE
AS
BEGIN
DELETE FROM JOB_REQUIREMENTS
WHERE CLASSID IN (SELECT CLASSID FROM DELETED)
END
GO