SELECT CASE
			WHEN
				CLASSES_TAKEN.CLASSID IS NULL
			THEN 'NO'
			ELSE 'YES'
		END
		AS 'TAKEN'
	FROM JOB
	JOIN APPLICATIONS
	ON JOB.JOB_ID = APPLICATIONS.JOBID
	LEFT JOIN CLASSES_TAKEN
	ON APPLICATIONS.STUDENTID = CLASSES_TAKEN.STUDENTID AND JOB.CLASSID = CLASSES_TAKEN.CLASSID;
GO

CREATE PROCEDURE filterApplicants
	@JOBID INT,
	@GPA FLOAT,
	@GRADE_LEVEL VARCHAR,
	@ORDER_SEMESTERS BIT,
	@ORDER_GPA BIT,
	@ORDER_TOOK_CLASS BIT
AS
	SELECT * FROM 
	(SELECT STUDENT.FIRST_NAME, STUDENT.LAST_NAME, STUDENT.GPA,
		STUDENT.SEMESTERS_COMPLETED, STUDENT.GRADE_LEVEL,

		CASE
			WHEN
				CLASSES_TAKEN.CLASSID IS NULL
			THEN 'NO'
			ELSE 'YES'
		END
		AS TAKEN1
	FROM JOB
	JOIN APPLICATIONS
	ON JOB.JOB_ID = APPLICATIONS.JOBID
	JOIN STUDENT
	ON STUDENT.STUDENTID = APPLICATIONS.STUDENTID
	LEFT JOIN CLASSES_TAKEN
	ON APPLICATIONS.STUDENTID = CLASSES_TAKEN.STUDENTID AND JOB.CLASSID = CLASSES_TAKEN.CLASSID
	WHERE JOB.JOB_ID = @JOBID) AS K
	ORDER BY
		CASE 
		WHEN @ORDER_GPA = 1 THEN GPA
		WHEN @ORDER_SEMESTERS = 1 THEN SEMESTERS_COMPLETED
		WHEN @ORDER_TOOK_CLASS = 1 THEN TAKEN1
		END DESC;
GO

-- JANKY AF BUT IT SHOULD DO THE TRICK\

-- This trigger should prevent anyone from applying for a job unless they have a gta cert

CREATE TRIGGER gtaCertRequired
	ON APPLICATIONS AFTER INSERT
	AS
		IF((SELECT TOP 1 STUDENT.GTA_CERT_LOCATION FROM STUDENT
		INNER join inserted
		ON inserted.STUDENTID = STUDENT.STUDENTID) IS NULL)
		BEGIN
			RAISERROR('Requirements not met',1,1);
			ROLLBACK
		END
GO