ALTER TABLE STUDENT
ALTER COLUMN FIRST_NAME VARCHAR(30) NOT NULL

ALTER TABLE STUDENT
ALTER COLUMN LAST_NAME VARCHAR(30) NOT NULL

ALTER TABLE STUDENT
ALTER COLUMN EMAIL VARCHAR(30)

ALTER TABLE STUDENT
ALTER COLUMN PHONE BIGINT

ALTER TABLE STUDENT
ALTER COLUMN GTA_CERT_LOCATION VARCHAR(30)

ALTER TABLE STUDENT
ALTER COLUMN CURRENT_MAJOR_FEILD VARCHAR(30)

ALTER TABLE STUDENT
ALTER COLUMN UNDERGRAD_DEGREE_TYPE VARCHAR(30)

ALTER TABLE STUDENT
ALTER COLUMN GRADE_LEVEL VARCHAR(30)

ALTER TABLE CLASSES
ALTER COLUMN DEPARTMENT VARCHAR(30) NOT NULL

DROP TABLE JOBTITLES

CREATE TABLE JOBTITLES
(TITLE VARCHAR(30) NOT NULL
CONSTRAINT PKJOBTITLES PRIMARY KEY(TITLE)
);

DROP TABLE DEPARTMENTS

CREATE TABLE DEPARTMENTS
(DEPTNAME VARCHAR(30) NOT NULL
CONSTRAINT PKDEPARTMENTS PRIMARY KEY(DEPTNAME)
);

ALTER TABLE JOB
ALTER COLUMN JOB_TITLE VARCHAR(30)

ALTER TABLE JOB
ALTER COLUMN TEACHER VARCHAR(30)

ALTER TABLE JOB
ALTER COLUMN JOB_DESCRIPTION VARCHAR(500) NOT NULL;

ALTER TABLE CLASSES_TAKEN
ALTER COLUMN LOCATION_TAKEN VARCHAR(30)

ALTER TABLE CLASSES
ALTER COLUMN CLASS_DESCRIPTION VARCHAR(500) NOT NULL;

